### PR TITLE
Update runtime, application, libraries, update patch for appdata

### PR DESCRIPTION
**Pull request by lionirdeadman**
It currently thinks there's no appdata, not entirely sure why.

### CODE REVIEW

**Comment by lionirdeadman** [comment]
I don't know how to fix the aarch64 build. Will look into appdata

**Review by hfiguiere — CHANGES_REQUESTED** [review]
With all of this it builds on Raspberry Pi.

**Comment by hfiguiere** [comment]
The upstream bug about the tarball https://github.com/naev/naev/issues/1827

**Comment by hfiguiere** [comment]
lgtm

**Review by hfiguiere — APPROVED** [review]

**Pull request merged**
